services:
  coffee-backend:
    container_name: coffee-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - postgres-db
    
  postgres-db:
    container_name: postgres-db
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db-data:
    driver: local
